export const originsInGroupsData = {
  value: [
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XboxComFD/origins/f4f92a10-5f6c-4913-bae1-90126bd0acb4",
      type: "Microsoft.Cdn/profiles/origingroups/origins",
      name: "f4f92a10-5f6c-4913-bae1-90126bd0acb4",
      properties: {
        originGroupName: "XboxComFD",
        hostName: "xbs-prod-eastus.trafficmanager.net",
        httpPort: 8761,
        httpsPort: 9761,
        originHostHeader: "xbs-prod-eastus.trafficmanager.net",
        priority: 1,
        weight: 50,
        enabledState: "Enabled",
        sharedPrivateLinkResource: null,
        enforceCertificateNameCheck: false,
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XboxComFD/origins/19117be1-c807-4a55-9d7f-dc003d77425d",
      type: "Microsoft.Cdn/profiles/origingroups/origins",
      name: "19117be1-c807-4a55-9d7f-dc003d77425d",
      properties: {
        originGroupName: "XboxComFD",
        hostName: "xbs-prod.westeurope.cloudapp.azure.com",
        httpPort: 8761,
        httpsPort: 9761,
        originHostHeader: "xbs-prod.westeurope.cloudapp.azure.com",
        priority: 1,
        weight: 50,
        enabledState: "Enabled",
        sharedPrivateLinkResource: null,
        enforceCertificateNameCheck: false,
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XboxComFD/origins/927bf748-22e6-4296-87e5-cd52078193fb",
      type: "Microsoft.Cdn/profiles/origingroups/origins",
      name: "927bf748-22e6-4296-87e5-cd52078193fb",
      properties: {
        originGroupName: "XboxComFD",
        hostName: "xbs-prod.westus2.cloudapp.azure.com",
        httpPort: 8761,
        httpsPort: 9761,
        originHostHeader: "xbs-prod.westus2.cloudapp.azure.com",
        priority: 1,
        weight: 50,
        enabledState: "Enabled",
        sharedPrivateLinkResource: null,
        enforceCertificateNameCheck: false,
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XboxComFD/origins/2988dda4-a474-4aa5-bc0b-12a2f4c79c6c",
      type: "Microsoft.Cdn/profiles/origingroups/origins",
      name: "2988dda4-a474-4aa5-bc0b-12a2f4c79c6c",
      properties: {
        originGroupName: "XboxComFD",
        hostName: "xbs-prod.southeastasia.cloudapp.azure.com",
        httpPort: 8761,
        httpsPort: 9761,
        originHostHeader: "xbs-prod.southeastasia.cloudapp.azure.com",
        priority: 1,
        weight: 50,
        enabledState: "Enabled",
        sharedPrivateLinkResource: null,
        enforceCertificateNameCheck: false,
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
  ],
};
