export const originGroupsData = {
  value: [
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XboxOneFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XboxOneFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/MercuryFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "MercuryFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XPRFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XPRFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XGuideFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XGuideFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/LegacyWishlistFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "LegacyWishlistFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XboxComFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XboxComFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/DigitalAttachmentFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "DigitalAttachmentFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XGeMPartnerCenterFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XGeMPartnerCenterFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/GPFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "GPFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XGuideSelfServeFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XGuideSelfServeFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XGeMWebFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XGeMWebFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XCatFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XCatFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/PurchaseExperienceFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "PurchaseExperienceFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XPurchaseFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XPurchaseFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/PCGAFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "PCGAFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/ExpectationsFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "ExpectationsFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XProductInsightsFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XProductInsightsFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/MojangFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "MojangFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/IrisFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "IrisFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/GriffinFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "GriffinFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/TitleHubFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "TitleHubFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/UbisoftFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "UbisoftFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/EntitlementsNotificationsFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "EntitlementsNotificationsFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/UHFFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "UHFFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/PurchaseNotificationFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "PurchaseNotificationFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/GDASFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "GDASFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XPackageFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XPackageFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XSaleWebFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XSaleWebFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/ProductConfigurationFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "ProductConfigurationFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "HEAD",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/XCloudFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "XCloudFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/GPIPFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "GPIPFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/NvidiaFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "NvidiaFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/StoreCartFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "StoreCartFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
    {
      id: "/subscriptions/3bd2aa80-029c-4b26-a621-a29a71807cc7/resourcegroups/XBET-Service/providers/Microsoft.Cdn/profiles/xbs-ms-afd-prod/origingroups/StreamingPartnerFD",
      type: "Microsoft.Cdn/profiles/origingroups",
      name: "StreamingPartnerFD",
      properties: {
        loadBalancingSettings: {
          sampleSize: 4,
          successfulSamplesRequired: 2,
          additionalLatencyInMilliseconds: 0,
        },
        healthProbeSettings: {
          probePath: "/servicestatus/health/reliability",
          probeRequestType: "GET",
          probeProtocol: "Https",
          probeIntervalInSeconds: 30,
        },
        trafficRestorationTimeToHealedOrNewEndpointsInMinutes: null,
        sessionAffinityState: "Disabled",
        provisioningState: "Succeeded",
        deploymentStatus: "NotStarted",
      },
    },
  ],
};
